pages/api/urls.py
from rest_framework import routers

from pages.api.views import PagesViewSet

app_name = 'pages'


router = routers.SimpleRouter()

router.register(r'pages', PagesViewSet, basename='pages')

urlpatterns = router.urls

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls.conf import include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(
        r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0),
        name='schema-json'
    ),
    re_path(
        r'^swagger/$',
        schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'
    ),

    path('api/v1/', include('pages.api.urls'), name='pages')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

pages/models.py
from ckeditor.fields import RichTextField
from django.core.validators import FileExtensionValidator
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from utils.text import translite


class PageManager(models.Manager):
    """Расширяем менеджер для страницы"""

    def search_pages_by_content(self, search_term):
        """Расширяю поиск в админке"""
        return (
            self.filter(
                Q(title__istartswith=search_term) |
                Q(audio__title__istartswith=search_term) |
                Q(video__title__istartswith=search_term) |
                Q(text__title__istartswith=search_term)
            ).distinct()
        )


class Page(models.Model):
    """Страница с контентом"""

    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True)

    objects = PageManager()

    class Meta:
        verbose_name = _('page')
        verbose_name_plural = _('pages')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = translite(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("pages:pages-detail", kwargs={"slug": self.slug})


class Content(models.Model):
    """Общее для всех страниц с контентом"""

    title = models.CharField(max_length=150, unique=True)
    counter = models.PositiveIntegerField(default=0)
    position = models.PositiveSmallIntegerField(default=0)
    page = models.ForeignKey(
        "pages.Page", null=True, blank=True, on_delete=models.SET_NULL
    )

    class Meta:
        abstract = True


class Video(Content):
    """Video контент"""

    file = models.FileField(
        upload_to='video/', max_length=180,
        validators=[
            FileExtensionValidator(
                allowed_extensions=['webm', 'avi', 'mp4', 'mov']
            )
        ],
    )
    subtitles = models.FileField(
        upload_to='subtitles/', max_length=180,
        validators=[
            FileExtensionValidator(
                allowed_extensions=['txt']
            )
        ],
    )

    class Meta:
        verbose_name = _('video')
        verbose_name_plural = _('video')

    def __str__(self):
        return self.title


class Audio(Content):
    """Аудио контент"""

    file = models.FileField(
        upload_to='audio/',
        validators=[
            FileExtensionValidator(allowed_extensions=['mp3', 'wav'])
        ],
    )
    bitrate = models.PositiveIntegerField()

    class Meta:
        verbose_name = _('audio')
        verbose_name_plural = _('audio')

    def __str__(self):
        return self.title


class Text(Content):
    """Text контент"""

    article = RichTextField()

    class Meta:
        verbose_name = _('text')
        verbose_name_plural = _('text')
        ordering = ['position']

    def __str__(self):
        return self.title


@receiver(pre_delete, sender=Audio)
def audio_clean(sender, instance, **kwargs):
    """Удаляем файл с диска"""
    if instance.file:
        instance.file.delete()


@receiver(pre_delete, sender=Video)
def video_clean(sender, instance, **kwargs):
    """Удаляем файлы с диска"""
    if instance.file:
        instance.file.delete()
    if instance.subtitles:
        instance.subtitles.delete()

users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

pages/api/views.py
from rest_framework import mixins, viewsets
from rest_framework.response import Response

from pages.api.serializers import PageDetailSerializer, PagesSerializer
from pages.models import Page


from pages.tasks import add_counter


class PagesViewSet(
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin,
    viewsets.GenericViewSet
):

    queryset = Page.objects.all()
    serializer_class = PagesSerializer

    lookup_field = 'slug'

    def get_serializer_class(self):
        serializers = {
            'retrieve': PageDetailSerializer,
        }
        return serializers.get(self.action, PagesSerializer)

    def retrieve(self, request, *args, **kwargs):
        page = self.get_object()

        add_counter.delay(page.id)

        serializer = self.get_serializer(page)
        return Response(serializer.data)

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NL</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
  {% block content %}{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>

templates/ckeditor/widget.html
{% load static %}
<div class="django-ckeditor-widget" data-field-id="{{id}}" style="display: inline-block;">
    <textarea{{ final_attrs }} data-processed="0" data-config="{{ config }}" data-external-plugin-resources="{{ external_plugin_resources }}" data-id="{{id}}" data-type="ckeditortype">{{ value }}</textarea>
</div>

templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Главная страница</h1>
<hr>
<a href="{% url 'pages:pages_list' %}">Список страниц с контентом</a>
<br>
<a href="api/v1/pages/">АПИ</a>
{% endblock content %}

templates/page_detail.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'pages:pages_list' %}">Вернуться к списку страниц</a>
<hr>
<h1>Page detail - {{ page.title }}</h1>

{% if page.content_set.exists %}

{% comment %} <h2>{{ page.content_set.title }}</h2> {% endcomment %}

<ul>

  {% for content in page.content_set.all %}

  {% if content.text %}
  {% include 'partials/text.html' with text=content.text %}
  {% endif %}

  {% if content.video %}
  {% include 'partials/video.html' with video=content.video  %}
  {% endif %}

  {% if content.audio %}
  {% include 'partials/audio.html' with audio=content.audio  %}
  {% endif %}

  {% endfor %}

</ul>
{% endif %}




{% endblock content %}

templates/pages_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'pages:home' %}">На главную</a>
<hr>
<h1>Pages list</h1>

<ul>
  {% for page in pages %}
  <li>
    <a href="{{ page.get_absolute_url }}">{{page}}</a>
  </li>
  {% endfor %}
</ul>

{% if page_obj.paginator.num_pages > 1 %}
<hr>
{% include 'partials/pagination.html' %}
{% endif %}
{% endblock content %}

templates/partials/audio.html
<li>
  АУДИО - {{audio.title}}
  <br>
  <audio controls="controls">
    <source src="{{ audio.file.url }}">
  </audio>
  <br>
  <p>Просмотров - {{audio.counter}}</p>
</li>

templates/partials/pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination">

    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    <li class="page-item">
      <a class="page-link" href="{% url 'pages:pages_list' %}?page={{num}}">{{ num }}</a>
    </li>
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% endif %}

  </ul>
</nav>

templates/partials/text.html
<li>
  ТЕКСТ - {{text.title}}
  <br>
  {{text.article|safe}}
  <br>
  <p>Просмотров - {{text.counter}}</p>
</li>

templates/partials/video.html
<li>
  ВИДЕО - {{ content.title }}
  <br>
  <video width="400" height="300" controls>
    <source src="{{ video.file.url }}">
  </video>
  <br>
  <p>Просмотров - {{video.counter}}</p>
</li>